src/Entity/Detalle.php
<?php

namespace App\Entity;

use App\Repository\DetalleRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DetalleRepository::class)
 */
class Detalle
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_vendedor;

    /**
     * @ORM\Column(type="integer")
     */
    private $numero_factura;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_articulo;

    /**
     * @ORM\Column(type="integer")
     */
    private $cantidad;

    /**
     * @ORM\Column(type="integer")
     */
    private $precio;

    /**
     * @ORM\Column(type="integer")
     */
    private $total;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdVendedor(): ?int
    {
        return $this->id_vendedor;
    }

    public function setIdVendedor(int $id_vendedor): self
    {
        $this->id_vendedor = $id_vendedor;

        return $this;
    }

    public function getNumeroFactura(): ?int
    {
        return $this->numero_factura;
    }

    public function setNumeroFactura(int $numero_factura): self
    {
        $this->numero_factura = $numero_factura;

        return $this;
    }

    public function getIdArticulo(): ?int
    {
        return $this->id_articulo;
    }

    public function setIdArticulo(int $id_articulo): self
    {
        $this->id_articulo = $id_articulo;

        return $this;
    }

    public function getCantidad(): ?int
    {
        return $this->cantidad;
    }

    public function setCantidad(int $cantidad): self
    {
        $this->cantidad = $cantidad;

        return $this;
    }

    public function getPrecio(): ?int
    {
        return $this->precio;
    }

    public function setPrecio(int $precio): self
    {
        $this->precio = $precio;

        return $this;
    }

    public function getTotal(): ?int
    {
        return $this->total;
    }

    public function setTotal(int $total): self
    {
        $this->total = $total;

        return $this;
    }
}

src/Entity/Direccion.php
<?php

namespace App\Entity;

use App\Repository\DireccionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DireccionRepository::class)
 */
class Direccion
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $via;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $numero;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $piso;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $puerta;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $cp;

    /**
     * @ORM\Column(type="string", length=80)
     */
    private $ciudad;

    /**
     * @ORM\Column(type="string", length=80)
     */
    private $estado;

    /**
     * @ORM\Column(type="string", length=80)
     */
    private $pais;

    /**
     * @ORM\OneToMany(targetEntity=Usuario::class, mappedBy="direccion", cascade={"persist"})
     */
    private $id_usuario;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $nombre_via;

    public function __construct()
    {
        $this->id_usuario = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getVia(): ?string
    {
        return $this->via;
    }

    public function setVia(string $via): self
    {
        $this->via = $via;

        return $this;
    }

    public function getNumero(): ?string
    {
        return $this->numero;
    }

    public function setNumero(string $numero): self
    {
        $this->numero = $numero;

        return $this;
    }

    public function getPiso(): ?string
    {
        return $this->piso;
    }

    public function setPiso(?string $piso): self
    {
        $this->piso = $piso;

        return $this;
    }

    public function getPuerta(): ?string
    {
        return $this->puerta;
    }

    public function setPuerta(?string $puerta): self
    {
        $this->puerta = $puerta;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(string $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getCiudad(): ?string
    {
        return $this->ciudad;
    }

    public function setCiudad(string $ciudad): self
    {
        $this->ciudad = $ciudad;

        return $this;
    }

    public function getEstado(): ?string
    {
        return $this->estado;
    }

    public function setEstado(string $estado): self
    {
        $this->estado = $estado;

        return $this;
    }

    public function getPais(): ?string
    {
        return $this->pais;
    }

    public function setPais(string $pais): self
    {
        $this->pais = $pais;

        return $this;
    }

    /**
     * @return Collection|Usuario[]
     */
    public function getIdUsuario(): Collection
    {
        return $this->id_usuario;
    }

    public function addIdUsuario(Usuario $idUsuario): self
    {
        if (!$this->id_usuario->contains($idUsuario)) {
            $this->id_usuario[] = $idUsuario;
            $idUsuario->setDireccion($this);
        }

        return $this;
    }

    public function removeIdUsuario(Usuario $idUsuario): self
    {
        if ($this->id_usuario->removeElement($idUsuario)) {
            // set the owning side to null (unless already changed)
            if ($idUsuario->getDireccion() === $this) {
                $idUsuario->setDireccion(null);
            }
        }

        return $this;
    }

    public function getNombreVia(): ?string
    {
        return $this->nombre_via;
    }

    public function setNombreVia(string $nombre_via): self
    {
        $this->nombre_via = $nombre_via;

        return $this;
    }
}

src/Entity/Usuario.php
<?php

namespace App\Entity;

use App\Repository\UsuarioRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UsuarioRepository::class)
 */
class Usuario implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Nombre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Apellido;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $Telefono;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $email;


    /**
     * @ORM\ManyToOne(targetEntity=Direccion::class, inversedBy="id_usuario")
     * @ORM\JoinColumn(nullable=false)
     */
    private $direccion;

    /**
     * @ORM\ManyToOne(targetEntity=Banco::class, inversedBy="id_usuario")
     * @ORM\JoinColumn(nullable=false)
     */
    private $banco;



    /**
     * @ORM\Column(type="string", length=150)
     */
    private $clave;

    /**
     * @ORM\Column(type="integer")
     */
    private $vendedor_id;



    public function getIdVendedor(): ?int
    {
        return $this->vendedor_id;
    }


    public function setIdVendedor($id_vendedor): self
    {
        $this->vendedor_id = $id_vendedor;
        return $this;
    }

    public function getClave(): ?string
    {
        return $this->clave;
    }


    public function setClave(string $clave): self
    {
        $this->clave = $clave;

        return $this;
    }


    private  $fecha;


    public function getFecha()
    {
        return $this->fecha;
    }


    public function setFecha($fecha): self
    {
        $this->fecha = $fecha;
        return $this;
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): self
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getApellido(): ?string
    {
        return $this->Apellido;
    }

    public function setApellido(string $Apellido): self
    {
        $this->Apellido = $Apellido;

        return $this;
    }

    public function getTelefono(): ?string
    {
        return $this->Telefono;
    }

    public function setTelefono(?string $Telefono): self
    {
        $this->Telefono = $Telefono;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getDireccion(): ?Direccion
    {
        return $this->direccion;
    }

    public function setDireccion(?Direccion $direccion): self
    {
        $this->direccion = $direccion;

        return $this;
    }

    public function getBanco(): ?Banco
    {
        return $this->banco;
    }

    public function setBanco(?Banco $banco): self
    {
        $this->banco = $banco;

        return $this;
    }

    /*public function getIdVendedor(): ?Vendedor
    {
        return $this->id_vendedor;
    }

    public function setIdVendedor(Vendedor $id_vendedor): self
    {
        // set the owning side of the relation if necessary
        if ($id_vendedor->getIdUsuario() !== $this) {
            $id_vendedor->setIdUsuario($this);
        }

        $this->id_vendedor = $id_vendedor;

        return $this;
    }*/


    public function getRoles()
    {
        return ['ROLE_USER'];
    }

    public function getPassword()
    {
        return $this->getClave();
    }

    public function getSalt()
    {
        return null;
    }

    public function getUsername()
    {
        return $this->getNombre();
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }
}

src/Controller/FacturaController.php
<?php

namespace App\Controller;


use App\Repository\ArticuloRepository;
use App\Repository\DetalleRepository;
use App\Repository\FacturaRepository;
use App\Repository\UsuarioRepository;
use App\Repository\ValoracionRepository;
use App\Service\SecurityManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class FacturaController extends AbstractController
{
    /**
     * @Route("/factura/{id<\d+>}/{usuario<\d+>}", name="factura", methods={"GET"}
     *     )
     * @param int $id
     * @param int $usuario
     * @param SecurityManager $securityManager
     * @param FacturaRepository $facturaRepository
     * @param DetalleRepository $detalleRepository
     * @param UsuarioRepository $usuarioRepository
     * @param ArticuloRepository $articuloRepository
     * @param ValoracionRepository $valoracionRepository
     * @param Request $request
     * @return Response
     */
    public function FacturaDetalle(int $id, int $usuario, SecurityManager $securityManager,
                   FacturaRepository $facturaRepository, DetalleRepository $detalleRepository,
                   UsuarioRepository $usuarioRepository, ArticuloRepository $articuloRepository,
                   ValoracionRepository $valoracionRepository, Request $request ): Response
    {
        if ($securityManager->chequeaUsuarioSolicitud($request,$usuario)){
            if($facturaSolicitada = $facturaRepository->find($id)){
                $detallesFactura = [];
                $detalles = $detalleRepository->findByFacturaId($facturaSolicitada->getId());
                foreach ($detalles as $detalle){
                    $vendedor = $usuarioRepository->findOneByIdVendedor($detalle->getIdVendedor());
                    $articulo = $articuloRepository->find($detalle->getIdArticulo());
                    $nombreVendedor = ucwords($vendedor->getNombre()." " . $vendedor->getApellido());
                    $valoracionArticuloValor = 0;
                    $idValoracion = 0 ;

                    if ($valoracionArticulo = $valoracionRepository->
                    findValoracionByClientArticuloAndFacturaId($usuario,$articulo->getId(),$facturaSolicitada->getId())){
                        $valoracionArticuloValor = $valoracionArticulo->getValor();
                        $idValoracion = $valoracionArticulo->getId();
                    }

                    $detallesFactura[] =
                        ['cantidad'=>$detalle->getCantidad(),'articulo'=> ucfirst($articulo->getNombre()),
                        'articuloId'=> $articulo->getId(),'precio' => $detalle->getPrecio(),
                        'total'=>$detalle->getTotal(),  'idVendedor'=> $vendedor->getId(),
                        'vendedor'=>$nombreVendedor, 'idDetalle'=>$detalle->getId(),
                        'valor' => $valoracionArticuloValor, 'idValoracion' => $idValoracion,
                            'perfilVendedor' => $vendedor->getIdVendedor(),
                        ];
                }
                $valoracionesUsuario = [];
                $valoraciones = $valoracionRepository->findByIdComprador($this->getUser()->getId());
                if (count($valoraciones)>0){
                    foreach ($valoraciones as $valoracionEach){
                        $valoracionesUsuario[] = $valoracionEach;
                    }

                }

                return $this->render('factura/detalle.html.twig', [
                    'factura' => $facturaSolicitada,
                    'detalles' => $detallesFactura,
                    'valoraciones'=>$valoraciones,
                ]);
            } else {
                $this->addFlash('fail','Factura'. $id .' no encontrada');
                return  $this->redirectToRoute('perfil_usuario',['id'=> $usuario]);
               // return $this->redirectToRoute('index');

            }

        } else {
            $this->addFlash('fail','Solo puedes ver tus facturas.');
            return $this->redirectToRoute('index');
        }

    }

    /**
     * @Route(
     *     "/facturas/{id<\d+>}/{pagina<\d+>}",
     *     name="facturas_usuario",
     *     defaults = {
     *     "pagina" = 1 },
     *     methods = { "GET" }
     *     )
     * @param int $id
     * @param int $pagina
     * @param UsuarioRepository $usuarioRepository
     * @param SecurityManager $securityManager
     * @param FacturaRepository $facturaRepository
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    public function mostrarTodasLasFacturasPorCliente(int $id, int $pagina, UsuarioRepository $usuarioRepository,
                                                      SecurityManager $securityManager, FacturaRepository $facturaRepository,
                                                      Request $request)
    {
        $ELEMENTOS_POR_PAGINA = 8;
        if ($securityManager->chequeaUsuarioSolicitud($request,$id)){
            if ($usuarioSolicitud = $usuarioRepository->find($id)){
                try {
                    $totalFacturasCliente = $facturaRepository->numeroFacturasPorCliente($id);
                } catch (\Exception $e){
                    $this->addFlash('fail','Ha ocurrido un error buscando tus facturas' . $e);
                    return  $this->redirectToRoute('index');
                }
                 if ($totalFacturasCliente==0){
                     $this->addFlash('fail','No se encontraron facturas disponible' );
                     return  $this->redirectToRoute('index');
                 }
                $numero_paginas = 1;
                $totalFacturasCliente > 0 ? $numero_paginas=ceil($totalFacturasCliente/$ELEMENTOS_POR_PAGINA) : $numero_paginas = 1;
                if ($pagina<1){
                    $pagina = 1;
                    return $this->redirectToRoute('facturas_usuario',['id'=>$id,'pagina'=> $pagina]);
                }
                if ($pagina>$numero_paginas){
                    return $this->redirectToRoute('facturas_usuario',['id'=>$id,'pagina'=> $numero_paginas]);
                }
                return $this->render('factura/facturas.html.twig',[
                    'facturas' => $facturaRepository->buscarFacturasPorUsuario($id,$pagina,$ELEMENTOS_POR_PAGINA),
                    'usuario' => $usuarioSolicitud,
                    'pagina_actual' => $pagina,
                    'total_elementos' => $totalFacturasCliente,
                    'numero_paginas' => $numero_paginas,
                    'gasto' => $facturaRepository->importeGastoPorUsuario($id)
                ]);
            } else{
                $this->addFlash('fail','No se ha encontrado el vendedor.');
                return  $this->redirectToRoute('index');
            }
        } else {
            $this->addFlash('fail','Solo puedes ver tus articulos.');
            return  $this->redirectToRoute('index');
        }
    }
}

templates/factura/detalle.html.twig
{% extends 'base.html.twig' %}

{% block title %}Factura{% endblock %}

{% block body %}

    <div class="container rounded contenedor">

        <div class="w-75 mx-auto p-3">
            <div class="d-flex justify-content-between">
                <h3>Factura {{ factura.id }}</h3>
                <h3>Fecha: {{ factura.fecha|date("m/d/Y") }}</h3>
            </div>
            <hr>
            <div>
                <h4>Cliente: {{ app.user.nombre|capitalize }} {{ app.user.apellido|capitalize }}</h4>
                <h4>Direccion:</h4>
                <h5>{{ app.user.direccion.via|capitalize }} {{ app.user.direccion.nombreVia|capitalize }} {{ app.user.direccion.numero|capitalize }}
                    {% if app.user.direccion.piso is not null %} piso {{ app.user.direccion.piso }} {% endif %}
                    {% if app.user.direccion.puerta is not null %} puerta {{ app.user.direccion.puerta|capitalize }}{% endif %}
                    .
                </h5>
                <h5>{{ app.user.direccion.ciudad|capitalize }} CP {{ app.user.direccion.cp }}
                    , {{ app.user.direccion.estado|capitalize }}
                    , {{ app.user.direccion.pais|capitalize }}.</h5>

            </div>

            <hr>
            <div class="">
                <table class="table table-hover text-center ">
                    <thead>
                    <tr class="table-dark text-white w-75 ">
                        <th class="col">Cantidad</th>
                        <th class="col">Articulo</th>
                        <th class="col  ">Precio</th>
                        <th class="col">Total</th>
                        <th class="col ">Vendedor</th>
                    </tr>

                    </thead>
                    <tbody>
                    {% for detalle in detalles %}

                        <tr>
                            <td class="col">{{ detalle.cantidad }}</td>
                            <td class="col"><a href="{{ path("articulo_show",{'id': detalle.articuloId}) }}"
                                               class="text-decoration-none text-dark"
                                               target="_blank" rel="noopener noreferrer">
                                    {{ detalle.articulo }}</a>
                            </td>
                            <td>{{ detalle.precio }} BC</td>

                            <td>{{ detalle.total }} BC</td>
                            <td>
                                <a href="{{ path('perfil_vendedor', { 'id' : detalle.perfilVendedor }) }}"
                                   class="text-decoration-none text-dark " target="_blank">
                                    {{ detalle.vendedor }}
                                </a>
                            </td>
                        </tr>


                    {% endfor %}
                    <tr class="table-secondary">
                        <td colspan="4" class="text-end"><strong> Importe Factura: {{ factura.importe }}</strong></td>
                        <td></td>
                    </tr>
                    </tbody>
                </table>
            </div>

            <hr>
            <h3 class="text-center mb-4">Valora tus productos</h3>
            <div class="border border-dark rounded contenedor p-4 ">
                <form action="{{ path('valoracion') }}" method="post"
                      onsubmit="return confirm('Estas seguro de la valoracion de el/los producto/s?');">
                    <input type="hidden" name="{{ 'idFactura' }}" value="{{ factura.id }}">
                    <input type="hidden" name="{{ 'idUsuario' }}" value="{{ app.user.id }}">

                    {% for detalle in detalles %}
                        <div class="row ">
                            <div class="col-md-10 mx-auto text-center">
                                <label for="{{ 'valoracion'~ detalle.articuloId }}" class="fs-5">Producto:
                                    <a href="{{ path("articulo_show",{'id': detalle.articuloId}) }}"
                                       class="text-dark" target="_blank"
                                       rel="noopener noreferrer"> {{ detalle.articulo }}</a>
                                    - Valoracion:
                                    <select name="{{ 'valoracion'~ detalle.articuloId }}" id="">
                                        {% for i in 0..5 %}
                                            {% set selected = '' %}
                                            {% if detalle.valor is same as (i) %}
                                                {% set selected = 'selected' %}
                                            {% endif %}
                                            <option value="{{ i }}"{{ selected }}>{{ i }}</option>
                                        {% endfor %}
                                    </select>
                                    <br> Vendedor: <a class="text-dark"
                                                      href="{{ path('perfil_vendedor', { 'id' : detalle.perfilVendedor }) }}">{{ detalle.vendedor }}</a>.
                                </label>

                                <input type="hidden" name="{{ 'idValoracion'~ detalle.articuloId }}"
                                       value="{{ detalle.idValoracion }}">
                                <input type="hidden" name="{{ 'articuloId'~ detalle.articuloId }}"
                                       value="{{ detalle.articuloId }}">
                                <input type="hidden" name="{{ 'vendedorId'~ detalle.articuloId }}"
                                       value="{{ detalle.idVendedor }}">
                                <input type="hidden" name="{{ 'idDetalle'~ detalle.articuloId }}"
                                       value="{{ detalle.idDetalle }}">

                            </div>
                        </div>
                        <br>
                    {% endfor %}
                    <div class="text-center">
                        <button type="submit" class="btn btn-success">Enviar Valoracion</button>
                    </div>
                </form>
            </div>
            <div class="mt-3 mb-1">
                <a href="{{ path('perfil_usuario', {'id': app.user.id}) }}"
                   class="text-decoration-none text-dark fs-3 ">
                    <img src="{{ asset('imagenes_articulos/arrow.png') }}" alt="Volver a mi perfil">
                    Volver a mi perfil
                </a>
            </div>
        </div>


    </div>


{% endblock %}

templates/factura/facturas.html.twig
{% extends 'base.html.twig' %}

{% block title %}Facturas{% endblock %}

{% block body %}
    <div class="container contenedor rounded p-3">
        <div class="text-center">
            <h3 class="text-decoration-underline">Facturas</h3>
        <table class="table w-75 mx-auto">
            <thead>
            <tr>
                <th scope="col" class="col-4"># </th>
                <th scope="col" class="col-4">Importe</th>
                <th scope="col" class="col-4">Fecha</th>
            </tr>
            </thead>
            <tbody>
            {% for  factura in facturas %}
                <tr>
                    <th scope="row" class="col-4">
                        <a href="{{ path('factura', {'id': factura.id, 'usuario' : usuario.id }) }}"
                           class="text-decoration-none text-dark" target="_blank">
                            {{ factura.id }}
                        </a>
                    </th>
                    <td class="col-4" >{{ factura.importe }} BC</td>
                    <td class="col-4" >{{ factura.fecha|date("m/d/Y") }}</td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="3" class="text-center">aun no tienes compras</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% if gasto > 0 %}
        <div>
            <h5>Has gastado <strong>{{ gasto }} BC</strong> en compras.</h5>
        </div>
    {% endif %}
</div>
        <div class="mt-3">
            {{
            include  (
                'comunes/_paginacion.html.twig', {
                numero_paginas : numero_paginas,
                pagina_actual : pagina_actual,
                'parametros_ruta' : { 'id' : app.user.id }

            }) }}

        </div>
    </div>
{% endblock %}